import { Inter, Alfa_Slab_One } from "next/font/google";
import "../assets/styles/globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const alfa = Alfa_Slab_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--alfa",
});
export const metadata = {
  title: "IUGB Website | Complete Redesign",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${alfa.variable} max-w-screen-3xl mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
